### PR TITLE
Updates to  country pages and backgrounders

### PR DESCRIPTION
**Pull request by tlongers**

### CODE REVIEW

**Comment by tlongers** [comment]
Ok @evz  I mucked up here: didn't see in my local copy you'd already added the new countries. Help!

**Comment by tlongers** [comment]
Thanks @evz - sorry about that.

**Comment by evz** [comment]
No problem! Merging now.

**Comment by evz** [comment]
Actually, I'm going to rebase this off of the branch that I currently have deployed on the production server. That way I don't have to do any git foo to make this work right away.

**Comment by evz** [comment]
OK I pulled out the relevant commits and put them into the branch that is on production: https://github.com/security-force-monitor/sfm-cms/commits/performance. Closing this in favor of that.

**Pull request closed without merging**
