### PR TITLE
[WIP] Rework how search is setup

### PR DESCRIPTION
**Pull request by evz**
This PR represents all of the things related to reconfiguring how we're doing search. I'm putting this up as a WIP mainly because I have a feeling I'm going to have questions and this will be a nice place to discuss them. 

Couple questions for @tonysecurityforcemonitor and @tlongers to start: 

* For things that will end up being indexed, do we want to worry about translations? As in, when I search in a given language version of the site, should I only get results in that language?
* If so, are all the languages that things will be stored in known? How often do you anticipate needing to add another language?

### CODE REVIEW

**Comment by tonysecurityforcemonitor** [comment]
> For things that will end up being indexed, do we want to worry about translations? As in, when I search in a given language version of the site, should I only get results in that language?

My hot take would be that a user should not only get results in the language that they searched in. Currently - we have at most entities in two languages for a country (Arabic and English), meaning not all People/Orgs/Events have both Arabic and English data associated with them, some only have Arabic and some only English.

> If so, are all the languages that things will be stored in known? How often do you anticipate needing to add another language?

I think we can easily develop a list - we don't have that much capacity for numerous languages. Currently we have: English, Spanish, Arabic and Portuguese.

**Comment by evz** [comment]
OK. Will any one thing ever be translated into more than English and something else? If you don't know right now, that's OK, too.

**Comment by tonysecurityforcemonitor** [comment]
> OK. Will any one thing ever be translated into more than English and something else? If you don't know right now, that's OK, too.

As of right now the only things that would have translations in multiple languages would be:
Organization Classification (i.e. every country would have Police)
Person Rank (i.e. Major General is a common rank across countries)
Person Role - Commander (we'd likely not have translations for every Role, but Commander is a standard role across countries)

**Comment by evz** [comment]
Great, this really helps. I'm hoping to bake this support into the search from the beginning so we don't have to retrofit later. 

One more question before lunch: In the current search, there's a way to search in a radius around a given location (either a site or an area). That doesn't seem to be suggested in the mockups. Is this something that we'd like to continue to support?

**Comment by tonysecurityforcemonitor** [comment]
> One more question before lunch: In the current search, there's a way to search in a radius around a given location (either a site or an area). That doesn't seem to be suggested in the mockups. Is this something that we'd like to continue to support?

Thanks for flagging that --- I think we should keep it. You're right we don't have a mockup, but I think the ability to do that could be a really powerful tool (caveat being not sure where/how to be implemented and that assumption is untested with users)...

**Comment by evz** [comment]
In the mockups there's not really a concept of a global search results page (meaning a results page with more than one entity type on it) but there is a big 'ol search box on the home page that should probably do something. So, I guess my question is: should we do away with the concept of a global search? If not, are there filters that we could display on the global search page that would relate to all the entity types that we are indexing? What @jeancochrane and I were just talking about was to have something like that on the global search and then have the more specific filters on the /persons/ and /organizations/ pages. Does that seem reasonable?

**Comment by tonysecurityforcemonitor** [comment]
Ah good point --- we were thinking that the big 'ol search box was a global search (correct me if I'm wrong here @tlongers ). In my mind a global search means when a user searches for "Central Police Station" it would pull up all the results related to Central Police Station - the organizations, people and events.

There aren't any really good filters that apply to every entity - geography would be the only filter I can thik of - but there is a BIG question on what that conveys to users...

> What @jeancochrane and I were just talking about was to have something like that on the global search and then have the more specific filters on the /persons/ and /organizations/ pages. Does that seem reasonable?

I can't quite visualize this, but it sounds like a good idea :)

**Comment by tlongers** [comment]
@evz said:
> If not, are there filters that we could display on the global search page that would relate to all the entity types that we are indexing?

Even with our signposting, users don't quite know what exactly they are going to find in the site. A global search gives them the chance to get stuck in and see. The record specific searches under /organizations  etc complement that. Is this the best solution though?

I had in mind a scoped search with options for "All records, "Organizations", "Personnel","Incidents" and "Sources" leading to a  results table with headings for Record type, Name, Country, earliest citation, last citation, and a catch-all field into which something relevant and descriptive from that entity could be piped (e.g. for "classification" for organizations , last known "rank" or "organization" for persons, type of event for "incidents"). 

However, even describing it sounds tedious and confusing so let's go with your suggestion @evz to force a choice of a single entity and then display the search at the appropriate url e.g. /organizations /persons and so on.

**Comment by tlongers** [comment]
@evz  said:
>One more question before lunch: In the current search, there's a way to search in a radius around a given location (either a site or an area). That doesn't seem to be suggested in the mockups. Is this something that we'd like to continue to support?

There is a geo search aspect,  included in the "location" facet on results pages. The design and implementation of a wider, map-based interaction with the data has to be done very carefully though, as it was the map that was widely reviled by users in the first cut. Users clearly want a map, and large parts of our data are essentially geographical, but the question of implementation is open. So, develop the backend functionality to do this, and we'll use it to edge forward with user feedback on how to make it work for them.

**Pull request merged**
